exclude: ^(.tox|doc|ci/templates|)(/|$)
repos:
  - repo: https://github.com/ambv/black
    rev: 085efac037c07ef299edbf48a4d871f17b296743
    hooks:
      - id: black
        args:
          - '--safe'
          - '--quiet'
          - '--line-length=120'
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 083b0d8174f80e7a4c4322800115d2dbede53980
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        files: mailie/
  - repo: https://github.com/PyCQA/flake8
    rev: c3ab1fcfb265e8509dd02c1e2367a07006f22c51
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: 071c722d2b36924e30c998a415609176e247fce5
    hooks:
      - id: pdb-vars
