exclude: ^(.tox|doc|ci/templates|)(/|$)
repos:
  - repo: https://github.com/ambv/black
    rev: b97ec62368ac57b29a0ccd5fc68ba875418eb8cc
    hooks:
      - id: black
        args:
          - '--safe'
          - '--quiet'
          - '--line-length=120'
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ccecdbda02e324779f1e18ae245c07ee923a8bae
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.920
    hooks:
      - id: mypy
        files: mailie/
  - repo: https://github.com/PyCQA/flake8
    rev: f90a549da5738e18342f496e083d60c05c618d09
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: 071c722d2b36924e30c998a415609176e247fce5
    hooks:
      - id: pdb-vars
