exclude: ^(.tox|doc|ci/templates|)(/|$)
repos:
  - repo: https://github.com/ambv/black
    rev: a18ee4018f855007bf4a23027a8d6478e56a36bf
    hooks:
      - id: black
        args:
          - '--safe'
          - '--quiet'
          - '--line-length=120'
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 083b0d8174f80e7a4c4322800115d2dbede53980
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        files: mailie/
  - repo: https://github.com/PyCQA/flake8
    rev: 7a02d04919a2209bc2612373d46d2edfa4d59773
    hooks:
      - id: flake8
  - repo: https://github.com/symonk/pre-commit-pdb-vars
    rev: 1d605b572d9b4d1e3ee9f592dec0fc2181dc2059
    hooks:
      - id: pdb-vars
