site_name: Mailie Documentation
site_url: https://www.google.com
nav:
    - Overview: index.md
    - Email: email.md
    - DSL: dsl.md
    - Commandline: commandline.md
theme:
  name: material

plugins:
    - search
    - mkdocstrings
